# Generated by Django 4.0.1 on 2022-08-17 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookie_stand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiestand',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_stand', to=settings.AUTH_USER_MODEL),
        ),
    ]
